# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Teste com maven
      run: mvn clean test site

    - name: Upload artefatos de teste
      uses: actions/upload-artifact@v3
      with:
        name: relatorio-testes
        path: C214---Exercicio-Teste-Mock/target/site/

  package:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven
      - name: Package with Maven
        run: mvn clean package
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Package-Artifact
          path: C214---Exercicio-Teste-Mock/target/*.jar

    scripts:

      needs: [ test, package ]
      runs-on: ubuntu-latest

      steps:
        - uses: actions/checkout@v3
        - name: Run Shell scripts
          run: sh scripts/sendEmail.sh
          env:
            EMAIL: antonio.v@ges.inatel.br